---
site:
  title: 'Liz: The Rancher AI Assistant'
  start_page: latest@rancher-ai:en:introduction.adoc

content:
  sources:
    - url: https://github.com/rancher/rancher-ai-product-docs.git
      branches: [main]
      start_paths: [shared, docs/latest]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-draft-preview-only: 'true'  # Comment whole line for false
    page-pagination: ""
    tabs-sync-option: ""
  extensions:
    - "@asciidoctor/tabs"

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts
      mermaid_initialize_options:
    - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
      attributefile: ./product-docs-common/global-attributes.yml
      enabled: true
    - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
      enabled: true

output:
  dir: build-remote/site
