name: Test deployment (minimum validations)

on:
  workflow_call:
    inputs:
      playbook-name:
        default: 'playbook-local.yml'
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  test-deploy:
    name: Test deployment (minimum validations)
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Checkout helper scripts
        uses: actions/checkout@v4
        with:
          repository: rancher/product-docs-common
          ref: main
          sparse-checkout: |
            scripts
          sparse-checkout-cone-mode: false
          path: helpers

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check revdate
        uses: rancher/product-docs-common/.github/actions/check-revdate-composite-action@main
        with:
          token: ${{ secrets.token }}

      - name: Install Antora and dependencies
        run: make environment

      - name: Generate Site
        run: |
          npx antora --stacktrace \
            --log-format=pretty \
            --log-level=info \
            ${{ inputs.playbook-name }}
            